### ISSUE TITLE
[BUG] Audio settings not being saved in presets

### ISSUE THREAD

**Issue by XCongoAlpha** [Alkl58/NotEnoughAV1Encodes#81] opened 2021-12-28 01:30 UTC
**Describe the bug**
When I am using a preset, only the video settings are applied.

**To Reproduce**
1. Make a preset with a different audio settings from default
2. Add source
3. Use preset
4. Audio settings is set back to the default opus 128kbps

**Expected behavior**
Output should have changed to the user set audio settings

**Desktop (please complete the following information):**
 - OS: Win10 1909
 - NEAV1E Version: 2.0.1

**Additional context**
Because it doesn't save audio settings, I have to manually edit items from the queue which makes life just a little more inconvenient.

**Comment by Alkl58** [comment] 2021-12-28 12:23
Duplicate of https://github.com/Alkl58/NotEnoughAV1Encodes/issues/80
Added/Fixed in https://github.com/Alkl58/NotEnoughAV1Encodes/commit/d6bc9ed067dadd367c20e47d264770e090411aaa

**Comment by Alkl58** [comment] 2021-12-28 14:09
Fixed Release: https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v2.0.2

**Closed by Alkl58** 2021-12-28 14:09 UTC
Labels: bug
