### ISSUE TITLE
Encode jobs merge with two instances active

### ISSUE THREAD

**Issue by darkcharmander** [Alkl58/NotEnoughAV1Encodes#6] opened 2020-06-04 08:55 UTC
I've had one job finished and started up a separate instance of the program.
After that second one was finished, I opened the result and I saw that it had like 10 seconds of footage from the previous encoding job. Thus the entire encoding had to be done again.

Don't know for sure how to reproduce it but I think you can do it the way that I did.

Edit: This doesn't always happen. Sometimes the program crashes right after splitting the job for the second instance. That is a separate problem which needs to be addressed.

**Comment by darkcharmander** [comment] 2020-06-04 12:05
I might be able to fix this myself since I've just installed Visual Studio. Need to find some free time for it.

**Comment by Alkl58** [comment] 2020-06-04 12:29
> I opened the result and I saw that it had like 10 seconds of footage from the previous encoding job.

You know that by default NEAV1E wont delete the temp files. This is a precaution, because Muxing Errors can appear and I didnt want people to waste their entire encoding. 
This means that they will be able to mux it themself, if something goes wrong.
The Problem is, that so far NEAV1E wont check if previous temp files exist, thus having these bugs you described. 
Deleting the files before starting a new encode, or checking the CheckBox "Delete Temp files after Encode" should solve your issue.

Correct me if I am wrong or understood something wrong. :)

**Comment by Alkl58** [comment] 2020-06-04 12:32
And why are you running two instances in the first place? 
NEAV1E is not programmed to be able to be run parallel from the same directory.

**Comment by darkcharmander** [comment] 2020-06-04 12:34
>And why are you running two instances in the first place?
NEAV1E is not programmed to be able to be run parallel from the same directory.
Because I want to encode separate files with different settings. Remembering the settings per file would be very awkward so I just open up a second instance and make that one start after the other one is done.

**Comment by master-of-zen** [comment] 2020-06-04 12:38
I want that too, add a new feature, now :smiley face: :knife:

**Comment by darkcharmander** [comment] 2020-06-04 12:44
> Because I want to encode separate files with different settings. Remembering the settings per file would be very awkward so I just open up a second instance and make that one start after the other one is done.

I have an idea on how that can be accomplished. The 'job recovery / resume session' thingy will need to become more complex and smarter. But it's doable. If I have some spare time tonight, and I get the code to compile in VS I might be able to make something. Can't guarantee it tough ;p

**Comment by Alkl58** [comment] 2020-06-04 12:47
Implementing the feature to be able to run two instances or more is a very deep change of the code.
You will see how bad my code is written, because all of the important functions (muxing, splitting, resume etc) are written for one specific folder structure.

In the meantime its much easier to just run the instances in two different folders.

**Comment by master-of-zen** [comment] 2020-06-05 08:00
Just do it

**Comment by Alkl58** [comment] 2020-07-20 16:09
Fixed with Commit 638dfd6

**Closed by Alkl58** 2020-07-20 16:09 UTC
