### ISSUE TITLE
Muxing failed video output not detected

### ISSUE THREAD

**Issue by nate-moo** [Alkl58/NotEnoughAV1Encodes#35] opened 2021-01-07 23:35 UTC
I can give anything needed at a later date

**Comment by mschlegel81** [comment] 2021-01-08 14:18
I had the same issue.
The input video was created from individual pictures using VirtualDub and saving as "uncompressed".

**Comment by Alkl58** [comment] 2021-01-08 14:55
Sorry, but I can't really help without further details.
1. What version of neav1e are you using?
2. Have you updated the dependencies?
3. Does it actually encode, or does it directly go to the muxing state? (encoder crashing)
4. Could you provide the log files?
5. Could you provde further video information with [MediaInfo](https://mediaarea.net/de/MediaInfo)?
6. Does this issue only appear on one certain video? Or does every encode crash?
7. Are there special non UTF characters in the path or filename?
8. What exact settings are being used?
What also helps, but is optional: Provide the source video so I can better reproduce this issue.
Many Greetings

**Comment by nate-moo** [comment] 2021-01-08 15:37
As of now it has been working, but I was using a 24 minute h264 video, and the video would fully encode but fail at finalizing (my assumption). I could click encode again with a different file name and extension and it would instantly encode but still fail.

**Comment by Alkl58** [comment] 2021-01-08 15:59
Then you can manually try the encoding step to see if there are erros. 
The used command can be found in the log file.
I can't really say other things, as the other questions have not been answered

**Comment by Alkl58** [comment] 2021-01-16 10:16
> As of now it has been working, but I was using a 24 minute h264 video, and the video would fully encode but fail at finalizing (my assumption). I could click encode again with a different file name and extension and it would instantly encode but still fail.

NEAV1E does try to automatically resume the encoding process, if the input file is the same and there had been a previous encoding attempt which is still in the temp folder.

All I can do for now is to say, that the next time you are experiencing this issue, please provide the log file. In that log file is also the muxing command which is being used. You may try executing the command manually, inorder to get the error message from the muxer. 
I will try to do some R&D how to parse error messages from the muxer.

**Comment by Alkl58** [comment] 2021-01-26 13:06
I am not sure, if I found the issue you have.
I got a no video output issue, when a preset overwrite the disabled audio toggle switch, thus it trying to encode audio, even tho the source does not have audio.
I fixed this particular bug in e1ffbe0e377a1e3c2d64a54e514a392adc87a548, and I also added a safeguard: f6a0d6f092f759a1384aaeeba558d7737040edfe

**Comment by nate-moo** [comment] 2021-01-26 14:28
I'll try it out, but I've just been using ffmpeg's AV1 encoder and its been working well for me

**Comment by nate-moo** [comment] 2021-01-26 14:37
After compiling the new version, I looks to just hang on encoding audio
[program.log](https://github.com/Alkl58/NotEnoughAV1Encodes/files/5873933/program.log)

**Comment by nate-moo** [comment] 2021-01-26 14:38
Ignore that last comment, I'm just a dummy

**Comment by nate-moo** [comment] 2021-01-26 14:47
Now I'm getting the error again and log file is attached along with a screenshot of my prefs
![image](https://user-images.githubusercontent.com/40650681/105860255-60a6cf80-5fbb-11eb-86e0-12e5cf9665fd.png)

```
1/26/2021 9:44:27 AM : FFmpeg Path: C:\ProgramData\chocolatey\bin
1/26/2021 9:44:27 AM : Aomenc Path: C:\Users\natha\path
1/26/2021 9:44:27 AM : Rav1e Path: 
1/26/2021 9:44:27 AM : SVT-AV1 Path: C:\Users\natha\path
1/26/2021 9:44:27 AM : VPXEnc Path: 
1/26/2021 9:44:27 AM : MKVToolNix Path: 
1/26/2021 9:44:27 AM : PySceneDetect found: False
1/26/2021 9:45:07 AM : Temp Path: C:\Users\natha\AppData\Local\Temp\NEAV1E
1/26/2021 9:45:07 AM : Aomenc Settings :  --bit-depth=8 --cpu-used=9 --end-usage=q --cq-level=63 --threads=4 --tile-columns=2 --tile-rows=1
1/26/2021 9:45:07 AM : Filter Command: 
1/26/2021 9:45:07 AM : Subtitle Command: 
1/26/2021 9:45:07 AM : Muxing: /C ffmpeg.exe -y -f concat -safe 0 -i "C:\Users\natha\AppData\Local\Temp\NEAV1E\nuts\Chunks\chunks.txt" -c copy "C:\Users\natha\AppData\Local\Temp\NEAV1E\nuts\temp.mkv"
1/26/2021 9:45:08 AM : Finished Encoding - Elapsed Time 00:00:01 - avg 4467.85fps
```

**Comment by Alkl58** [comment] 2021-01-26 15:07
Would it be possible to provide the source video file?
Also try to clear the the temp folder, as it seem to have completely skip the encoding process.

**Comment by nate-moo** [comment] 2021-01-26 15:23
It is now encoding just by clearing the temp folder, will report when video is done. If it errors I'll supply the video

**Comment by nate-moo** [comment] 2021-01-26 15:28
It finished with no errors, I think it has to do with something being recoded with the same filename which messes the muxing up

**Comment by nate-moo** [comment] 2021-01-26 15:35
or not as it just worked again. Maybe I've just been getting corrupt temp files which screwed me over. Anyhow thanks for your time and I'll report back later if It fails again.

**Comment by mschlegel81** [comment] 2021-01-26 16:30
I just wanted to add that I was not able to reproduce the issue.
For the time being it works for me. Thank you for your time and your great project.

**Comment by Alkl58** [comment] 2021-02-22 18:06
Issue seems to be resolved. Closing it now.
Feel free to reopen a new issue, if you still experience it.
Many Greetings

**Comment by nate-moo** [comment] 2021-03-02 18:03
on a fresh install it just happened again. looking at the log it looks like it is mkvmerge that is failing

**Comment by Alkl58** [comment] 2021-03-02 20:37
Can you provide the log file?

**Comment by nate-moo** [comment] 2021-03-03 15:53
I will if I have time in-between work and school later today

**Comment by nate-moo** [comment] 2021-03-05 11:32
[program.log](https://github.com/Alkl58/NotEnoughAV1Encodes/files/6090184/program.log)
it looks like it finished in the log but it never outputs any file

**Comment by Alkl58** [comment] 2021-03-05 12:18
WebM does not support subtitles ^^'

**Comment by nate-moo** [comment] 2021-03-05 12:19
Oh... I thought it did, welp ig I should just use mkv then?

**Comment by Alkl58** [comment] 2021-03-05 12:23
Yes, either use mkv as container, or if you really need webm you can try burning in the subtitles. 

In theory, if you have not yet deleted the temp files, all you need to do is selecting the same settings / input video / project file and set the output to mkv, it should mux it.

**Comment by nate-moo** [comment] 2021-03-05 12:25
Neat, will do. Thanks for the help!

**Comment by nate-moo** [comment] 2021-03-05 12:43
Are you able to do a sub conversion to vtt using ffmpeg or something. iirc vtt is sorted by webm

**Comment by Alkl58** [comment] 2021-03-05 12:59
In theory it would work, the problem is that converting ass subtitles to vtt is always a hit or miss.
Depending on the ass subtitles, it could lead to lot's of weird behavior (subtitle effects, commentary which shouldn't be displayed etc)

**Comment by nate-moo** [comment] 2021-03-05 13:01
Ah, well it was worth an ask

**Closed** 2021-06-02 15:05 UTC
