### ISSUE TITLE
Check Updates not working

### ISSUE THREAD

**Issue by Piqlet** [Alkl58/NotEnoughAV1Encodes#15] opened 2020-09-04 07:56 UTC
(1.) Start and Check Updates button. Win 7 x64, ver.:1.2 

![neav1_error_3_256](https://user-images.githubusercontent.com/16097403/92213111-4dbc2300-ee93-11ea-987e-877570727b22.png)
![neav1_error_4_256](https://user-images.githubusercontent.com/16097403/92213132-53b20400-ee93-11ea-8cea-12fc3c2faf6d.png)

program.log :
```
2020.09.04. 9:11:10 : Program Version: 1.2
2020.09.04. 9:11:11 : System Core Count: 4
2020.09.04. 9:11:11 : Encoder aomenc Path: 
2020.09.04. 9:11:11 : Encoder rav1e Path: 
2020.09.04. 9:11:11 : Encoder svt-av1 Path: 
2020.09.04. 9:11:11 : Encoder ffmpeg Path: 
2020.09.04. 9:11:11 : Encoder ffprobe Path: 
2020.09.04. 9:12:06 : Program Version: 1.2
2020.09.04. 9:12:07 : System Core Count: 4
2020.09.04. 9:12:07 : Encoder aomenc Path: 
2020.09.04. 9:12:07 : Encoder rav1e Path: 
2020.09.04. 9:12:07 : Encoder svt-av1 Path: 
2020.09.04. 9:12:07 : Encoder ffmpeg Path: 
2020.09.04. 9:12:07 : Encoder ffprobe Path: 
2020.09.04. 9:14:17 : Program Version: 1.2
2020.09.04. 9:14:18 : System Core Count: 4
2020.09.04. 9:14:18 : Encoder aomenc Path: 
2020.09.04. 9:14:18 : Encoder rav1e Path: 
2020.09.04. 9:14:18 : Encoder svt-av1 Path: 
2020.09.04. 9:14:18 : Encoder ffmpeg Path: 
2020.09.04. 9:14:18 : Encoder ffprobe Path: 
2020.09.04. 9:16:58 : Program Version: 1.2
2020.09.04. 9:16:59 : System Core Count: 4
2020.09.04. 9:16:59 : Encoder aomenc Path: 
2020.09.04. 9:16:59 : Encoder rav1e Path: 
2020.09.04. 9:16:59 : Encoder svt-av1 Path: 
2020.09.04. 9:16:59 : Encoder ffmpeg Path: 
2020.09.04. 9:16:59 : Encoder ffprobe Path: 
2020.09.04. 9:18:00 : Program Version: 1.2
2020.09.04. 9:18:01 : System Core Count: 4
2020.09.04. 9:18:01 : Encoder aomenc Path: 
2020.09.04. 9:18:01 : Encoder rav1e Path: 
2020.09.04. 9:18:01 : Encoder svt-av1 Path: 
2020.09.04. 9:18:01 : Encoder ffmpeg Path: C:\AMD\NEAV1\NotEnoughAV1Encodes\Apps\ffmpeg
2020.09.04. 9:18:01 : Encoder ffprobe Path: C:\AMD\NEAV1\NotEnoughAV1Encodes\Apps\ffmpeg
2020.09.04. 9:23:19 : Program Version: 1.2
2020.09.04. 9:23:20 : System Core Count: 4
2020.09.04. 9:23:20 : Encoder aomenc Path: C:\AMD\NEAV1\NotEnoughAV1Encodes\Apps\Encoder
2020.09.04. 9:23:20 : Encoder rav1e Path: C:\AMD\NEAV1\NotEnoughAV1Encodes\Apps\Encoder
2020.09.04. 9:23:20 : Encoder svt-av1 Path: C:\AMD\NEAV1\NotEnoughAV1Encodes\Apps\Encoder
2020.09.04. 9:23:20 : Encoder ffmpeg Path: C:\AMD\NEAV1\NotEnoughAV1Encodes\Apps\ffmpeg
2020.09.04. 9:23:20 : Encoder ffprobe Path: C:\AMD\NEAV1\NotEnoughAV1Encodes\Apps\ffmpeg
2020.09.04. 9:26:44 : Program Version: 1.2
2020.09.04. 9:26:45 : System Core Count: 4
2020.09.04. 9:26:45 : Encoder aomenc Path: C:\AMD\NEAV1\NotEnoughAV1Encodes\Apps\Encoder
2020.09.04. 9:26:45 : Encoder rav1e Path: C:\AMD\NEAV1\NotEnoughAV1Encodes\Apps\Encoder
2020.09.04. 9:26:45 : Encoder svt-av1 Path: C:\AMD\NEAV1\NotEnoughAV1Encodes\Apps\Encoder
2020.09.04. 9:26:45 : Encoder ffmpeg Path: C:\AMD\NEAV1\NotEnoughAV1Encodes\Apps\ffmpeg
2020.09.04. 9:26:45 : Encoder ffprobe Path: C:\AMD\NEAV1\NotEnoughAV1Encodes\Apps\ffmpeg
```
Manual add ffmpeg and Encoder content run OK.

(2.) I try delete and reinstall, but not help.

(3.) Portable mode another message 09 : System.Windows.Markup.XamlParse

![neav1_error_5_256](https://user-images.githubusercontent.com/16097403/92216871-2e26f980-ee97-11ea-8ace-69b38d1f07ee.png)

**Comment by Alkl58** [comment] 2020-09-04 11:00
I installed Windows 7 VM, as I could not reproduce the error on Windows 10.

With the Windows 7 VM I successfully reproduced your issues. 

First I thought it to be an issue witth the new way how I parse directly from Github, but after I disabled Github Parsing I found the issue to be present also with parsing from the builds from https://jeremylee.sh/bin.html

I will further investigate how to solve this issue, but I can't promise a fix. 
In the meantime you may download the dependencies manually. I highly recommend https://jeremylee.sh/bin.html

**Comment by Alkl58** [comment] 2020-09-04 19:49
I identified the issue: The Problem was that .NET Framework does not have TLS/SSL activated by default, resulting in an unhandled error. 

You can download the latest Build including that Patch here: [click](https://ci.appveyor.com/project/Alkl/notenoughav1encodes/build/artifacts)

Many Greetings

**Comment by Piqlet** [comment] 2020-09-04 20:28
Works fine.

![neav1_good_5_256](https://user-images.githubusercontent.com/16097403/92282276-8c86c300-eefd-11ea-9e82-26df3bf0860f.png)

Thanks great work.

**Comment by Alkl58** [comment] 2020-09-04 20:30
Thats great to hear :)

I will close the issue now.

Many Greetings

**Closed by Alkl58** 2020-09-04 20:30 UTC
Labels: bug
