### ISSUE TITLE
Crop Not Work 

### ISSUE THREAD

**Issue by Serchrepo** [Alkl58/NotEnoughAV1Encodes#146] opened 2023-07-22 11:40 UTC
Croup Future Not Working Can fix this?

**Comment by Shanti099** [comment] 2023-08-15 16:26
issue confirmed,
if you crop and resize 4k at the same time, the frame is first resized and then cropped as 4k,
which causes incorrect resizing. instead of 1920x800, it turns out to 1920x500
instead of 264 px, filter cropped 528 px of 1920x800. 

![Example of cropping](https://github.com/Alkl58/NotEnoughAV1Encodes/assets/75264617/a5ef80f6-5a4a-4c1c-be03-c12e4fac3495)
__
so, to fix it, crop filter should read / check if resize filter is active and read size parameters of the resized frame first and then be cropped correctly.

**Comment by Alkl58** [comment] 2023-09-21 12:06
Fixed in new [Release v2.1.5](https://github.com/Alkl58/NotEnoughAV1Encodes/releases/tag/v2.1.5).

**Closed by Alkl58** 2023-09-21 12:06 UTC
Labels: enhancement
